name: UCL-sketch
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.8.13
  - pytorch=2.0.1
  - pip:
    - numpy
    - tqdm
    - matplotlib
    - scikit-learn
    - bitarray
    - scipy
    - seaborn
